### ISSUE TITLE
Error Orders

### ISSUE THREAD

**Issue by alejandromultiplicalia** [Matt75/displayordercarrier#1]
I have installed the module, and it gives me an error in some functions, after installation.
This error occurs in the list of orders

**Comment by Matt75** [comment]
Hello @alejandromultiplicalia 
Can you tell me more about the error ?
Did you have some logs, error trace or screenshots ?
What is your PrestaShop version ?

**Comment by alejandromultiplicalia** [comment]
am attaching a screenshot, so you can see the error.
I am using prestashop, 1.7.7.3




-- 
Alejandro Vázquez González

Desarrollador Web
 
Teléfono: 954 10 48 06
Mail: ***@***.***

Esta comunicación va dirigida exclusivamente al receptor o receptora de este mensaje y contiene información que es legalmente privilegiada, confidencial o tiene prohibida su difusión. Si usted no es el receptor o receptora de este mensaje, por favor sepa que cualquier difusión, distribución o copia de esta comunicación queda estrictamente prohibida. Quien quiera que reciba este mensaje por error deberá notificar al emisor o emisora inmediatamente y deberá eliminar este mensaje de su ordenador. Proteja al medio ambiente: no imprima este correo si no es necesario.
This communication is intended solely for the use of the addressee and contains information that is legally privileged, confidential or exempt from disclosure. If you are not the intended recipient, please note that any dissemination, distribution or copying of this communication is strictly prohibited. Anyone who receives this message in error should notify the sender immediately and delete it from his or her computer. Protect the environment: do not print this message unless necessary.

De: Matt75
Enviado: lunes, 3 de mayo de 2021 17:44
Para: Matt75/displayordercarrier
CC: alejandromultiplicalia; Mention
Asunto: Re: [Matt75/displayordercarrier] Error Orders (#1)

Hello @alejandromultiplicalia
Can you tell me more about the error ?
Did you have some logs, error trace or screenshots ?
What is your PrestaShop version ?

**Comment by Matt75** [comment]
Please reply on GitHub because attachment by email is not working, I can't see your screenshot.
https://github.com/Matt75/displayordercarrier/issues/1

**Comment by alejandromultiplicalia** [comment]
![Captura Error](https://user-images.githubusercontent.com/83599225/116968701-49ac0380-acb5-11eb-9140-d70c84514783.png)

**Comment by Matt75** [comment]
Did you install this module with the ZIP displayordercarrier.zip
 available here : https://github.com/Matt75/displayordercarrier/releases/latest ?

I did not manage to reproduce your issue, can you try to clear cache ?
