### ISSUE TITLE
Error after uploading module

### ISSUE THREAD

**Issue by chatlumo** [Matt75/displayordercarrier#7]
**Describe the bug**
Hello,

When uploading the module in "modules" directory, I then get an error message in the back office, which reads:
```
Compile Error: require(): Failed opening required '/home/www/boutiquenew/www/modules/displayordercarrier/vendor/autoload. php' (include_path='/home/www/boutiquenew/www/vendor/pear/pear_exception:/home/www/boutiquenew/www/vendor/pear/console_getopt:/home/www/boutiquenew/www/vendor/pear/pear-core-minimal/src:/home/www/boutiquenew/www/vendor/pear/archive_tar:. :/opt/remi/php74/root/usr/share/pear:/opt/remi/php74/root/usr/share/php:/usr/share/pear:/usr/share/php')

[Symfony\Component\Debug\Exception\FatalErrorException 0]
``` 

Est-ce un problème de compatibilité avec Prestashop ou PHP ?

**Additionnal information**
PrestaShop version: 1.7.8.7
PHP version: 7.4.16

**Comment by Matt75** [comment]
Run `composer install`
Or download the release ZIP (not source code !) https://github.com/Matt75/displayordercarrier/releases/latest

**Comment by chatlumo** [comment]
Thanks, it’s work like a charm.
