### ISSUE TITLE
Compatibility with PrestaShop 7 and 8?

### ISSUE THREAD

**Issue by Marcel15** [Matt75/displayordercarrier#8]
Hello,

I have been using your module since version 1.7.6.8, and I would like to know if it is now compatible with PrestaShop version 8 and later. Thank you in advance for your response.
philippe

**Comment by Matt75** [comment]
Hello @Marcel15 

Yes, it works with PrestaShop 1.7 & 8.x

You have to use the latest version available here: https://github.com/Matt75/displayordercarrier/releases/latest

**Comment by Marcel15** [comment]
Merci
